"""Fixed game model

Revision ID: 617abc27ef2c
Revises: f410e98ec915
Create Date: 2022-09-19 00:36:30.537786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '617abc27ef2c'
down_revision = 'f410e98ec915'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
