"""Added game table

Revision ID: bc10e0337069
Revises: 53236d9f8f3f
Create Date: 2022-09-17 23:40:03.971418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc10e0337069'
down_revision = '53236d9f8f3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
