"""Change game model

Revision ID: cd250f39a1a6
Revises: b195070ae017
Create Date: 2022-09-19 00:13:33.473936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd250f39a1a6'
down_revision = 'b195070ae017'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('word_id', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('word_state', sa.String(), nullable=True))
    op.add_column('games', sa.Column('whos_step', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('deadline', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'games', 'words', ['word_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'games', 'users', ['whos_step'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_column('games', 'deadline')
    op.drop_column('games', 'whos_step')
    op.drop_column('games', 'word_state')
    op.drop_column('games', 'word_id')
    # ### end Alembic commands ###
