"""Fixed game model

Revision ID: d86d19dd504d
Revises: cd250f39a1a6
Create Date: 2022-09-19 00:29:10.108463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd86d19dd504d'
down_revision = 'cd250f39a1a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('games_whos_step_fkey', 'games', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('games_whos_step_fkey', 'games', 'users', ['whos_step'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
