"""Fixed game model

Revision ID: f410e98ec915
Revises: d86d19dd504d
Create Date: 2022-09-19 00:33:07.760948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f410e98ec915'
down_revision = 'd86d19dd504d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
